export const refs = {
  formSearch: document.querySelector('.header__form'),
  galleryContainer: document.querySelector('.gallery'),
  filmsContainer: document.querySelector('.film__list'),
  closeModalBtn: document.querySelector('.modal-closeButton'),
  backdrop: document.querySelector('.modal-backdrop'),
  modalContainer: document.querySelector('.modal-container'),
  modalBtnEl: document.querySelector('.modal-button'),
  // modalListEl: document.querySelector('.modal-button-list'),
  pagination: document.querySelector('.pagination'),
  footerLink: document.querySelector('.footer-link'),
  footerBackdrop: document.querySelector('.footer-backdrop'),
  footerCloseModalBtn: document.querySelector('.footer-closeModalBtn'),
  scrollOnModal: document.querySelector('body'),
  trailerBtn: document.querySelector('.trailer'),
};
