export const refs = {
  header: document.querySelector('.js-header'),
  headerLogo: document.querySelector('.js-logo'),
  headerHomePage: document.querySelector('.js-home-page'),
  headerContainer: document.querySelector('.js-header-container'),
  myLibraryBtn: document.querySelector('.js-library-btn'),
  formSearch: document.querySelector('.header__form'),
  galleryContainer: document.querySelector('.gallery'),
  filmsContainer: document.querySelector('.film__list'),
  closeModalBtn: document.querySelector('.modal-closeButton'),
  backdrop: document.querySelector('.modal-backdrop'),
  modalContainer: document.querySelector('.modal-container'),
  modalBtnEl: document.querySelector('.modal-button'),
  pagination: document.querySelector('.pagination'),
  footerLink: document.querySelector('.footer-link'),
  footerBackdrop: document.querySelector('.footer-backdrop'),
  footerCloseModalBtn: document.querySelector('.footer-closeModalBtn'),
  scrollOnModal: document.querySelector('body'),
  trailerBtn: document.querySelector('.trailer'),
  scrollToTopBtn: document.querySelector('.js-scroll-to-top-btn'),
  openLoginModalBtn: document.querySelector('.js-loginModal-openBtn'),
  backdropLogin: document.querySelector('.modalLogin-backdrop'),
  closeLoginModalBtn: document.querySelector('.js-loginModal-closeButton'),
  openLibrary: document.querySelector('.js-openLibrary'),
  backDropLibrary: document.querySelector('.js-backDropLibrary'),
  logOutRef: document.querySelector('.js-logOutRef'),
};
