import './sass/main.scss';
import './js/refs.js';
import './js/api.js';
import './js/onSearchByKeyWord.js';
import './js/pagination';
import './js/renderTrendsOnMain.js';
import './js/modal.js';
import './js/footerModal';
// import './js/myLibrary';
import './js/switcher';
import './js/trailer';
import './js/my-library/myLibraryBtn';
import './js/scrollToTopBtn';
